// <auto-generated />
using BlackPearl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackPearl.Migrations
{
    [DbContext(typeof(BlackPearl))]
    [Migration("20220315135558_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("BlackPearl.Pearl", b =>
                {
                    b.Property<int>("NecklaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("Diameter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shape")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("NecklaceID");

                    b.ToTable("Pearls");
                });

            modelBuilder.Entity("BlackPearl.PearlList", b =>
                {
                    b.Property<int>("NecklaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("NecklaceID");

                    b.ToTable("PearlLists");
                });
#pragma warning restore 612, 618
        }
    }
}
